const harvesterBody = {
"1" :[WORK,WORK,MOVE,CARRY],
"2" : [WORK,WORK,WORK,MOVE,CARRY],
"3" : [WORK,WORK,WORK,WORK,WORK,MOVE,MOVE,CARRY],
"4" : [WORK,WORK,WORK,WORK,WORK,WORK,MOVE,MOVE,CARRY,CARRY],
"5" : [WORK,WORK,WORK,WORK,WORK,WORK,MOVE,MOVE,CARRY,CARRY],
"6" : [WORK,WORK,WORK,WORK,WORK,WORK,MOVE,MOVE,CARRY,CARRY],
"7" : [WORK,WORK,WORK,WORK,WORK,WORK,MOVE,MOVE,CARRY,CARRY],
"8" : [WORK,WORK,WORK,WORK,WORK,WORK,MOVE,MOVE,CARRY,CARRY]
}


const upgraderBody = {
"1" :[WORK,MOVE,CARRY],
"2" : [WORK,WORK,MOVE,CARRY],
"3" : [WORK,WORK,WORK,WORK,MOVE,MOVE,CARRY, CARRY],
"4" : [WORK,WORK,WORK,WORK,WORK,MOVE,MOVE,CARRY,CARRY],
"5" : [WORK,WORK,WORK,WORK,WORK,WORK,MOVE,MOVE,CARRY,CARRY],
"6" : [WORK,WORK,WORK,WORK,WORK,WORK,MOVE,MOVE,CARRY,CARRY],
"7" : [WORK,WORK,WORK,WORK,WORK,WORK,MOVE,MOVE,CARRY,CARRY],
"8" : [WORK,WORK,WORK,WORK,WORK,WORK,MOVE,MOVE,CARRY,CARRY]
}


const fillerBody = {
"1" : [CARRY,CARRY,MOVE,MOVE],
"2" : [CARRY,CARRY,CARRY,MOVE,MOVE],
"3" : [CARRY,CARRY,CARRY,MOVE,MOVE,MOVE],
"4" : [CARRY,CARRY,CARRY,CARRY,MOVE,MOVE,MOVE,MOVE],
"5" : [CARRY,CARRY,CARRY,CARRY,MOVE,MOVE,MOVE,MOVE],
"6" : [CARRY,CARRY,CARRY,CARRY,CARRY,MOVE,MOVE,MOVE,MOVE,MOVE],
"7" : [CARRY,CARRY,CARRY,CARRY,CARRY,MOVE,MOVE,MOVE,MOVE,MOVE],
"8" : [CARRY,CARRY,CARRY,CARRY,CARRY,MOVE,MOVE,MOVE,MOVE,MOVE]
}


const simpleBody = {
"1" :[WORK,MOVE,CARRY],
"2" : [WORK,WORK,MOVE,CARRY],
"3" : [WORK,WORK,MOVE,MOVE,CARRY,CARRY],
"4" : [WORK,WORK,MOVE,MOVE,CARRY,CARRY],
"5" : [WORK,WORK,MOVE,MOVE,MOVE,CARRY,CARRY,CARRY],
"6" : [WORK,WORK,WORK,MOVE,MOVE,MOVE,CARRY,CARRY,CARRY],
"7" : [WORK,WORK,WORK,MOVE,MOVE,MOVE,CARRY,CARRY,CARRY],
"8" : [WORK,WORK,WORK,MOVE,MOVE,MOVE,CARRY,CARRY,CARRY]
}








module.exports ={
  run: function(creepType, level){
//console.log(creepType + "    " + parseInt(level, 10));


if(creepType === 'harvester'){
  return harvesterBody[parseInt(level, 10)];
}
if(creepType === 'upgrader'){
  return upgraderBody[parseInt(level, 10)];
}
if(creepType === 'filler'){
  return fillerBody[parseInt(level, 10)];
}
if(creepType === 'simple'){
  return simpleBody[parseInt(level, 10)];
}











  }
}
